# site settings
title: Croak and Bloom
subtitle: Handmade Pottery and Gifts
email: anna@croakandbloom.com
description: 🙌 Small-batch Pottery & Giftware. As featured on BuzzFeed, The Seattle Times, and Washington Wedding Day Magazine 🥂 Wholesale/Custom/Collabs 💌 DM
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Anna
street_address:
city: Bellingham
state: WA
zip_code: 98226
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/croakandbloom/
  LinkedIn: https://www.linkedin.com/in/anna-poupa-tsikerdekis-b88a345b/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
